# Generated by Django 2.0.2 on 2020-05-05 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_num', models.PositiveSmallIntegerField()),
                ('dep_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_num', models.PositiveSmallIntegerField()),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_ename', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('女', 'Female'), ('男', 'Male')], max_length=1)),
                ('birth', models.DateField()),
                ('age', models.PositiveSmallIntegerField()),
                ('bloodtype', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=1)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='empapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_num', models.PositiveSmallIntegerField()),
                ('job_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='empapp.job'),
        ),
    ]
