# Generated by Django 2.0.2 on 2020-05-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dep',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.DeleteModel(
            name='job',
        ),
    ]
