# Generated by Django 2.0.2 on 2020-05-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_auto_20200505_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth',
            field=models.CharField(max_length=30),
        ),
    ]
