# Generated by Django 2.0.2 on 2020-05-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_auto_20200505_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bloodtype',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2),
        ),
    ]
