# Generated by Django 2.0.2 on 2020-05-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_auto_20200506_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField()),
                ('lname', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('elname', models.CharField(max_length=30)),
                ('efname', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('女', 'Female'), ('男', 'Male')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('birth', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('bloodtype', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('dep', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=30)),
                ('pw', models.CharField(max_length=30)),
            ],
        ),
    ]
