# Generated by Django 2.0.2 on 2020-05-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0005_employeedetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='dep',
            field=models.CharField(choices=[('営業', 'sales'), ('広報', 'pr'), ('開発', 'dev')], max_length=2),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='job',
            field=models.CharField(choices=[('一般', 'regular'), ('組織長', 'administrator')], max_length=3),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='sex',
            field=models.CharField(choices=[('女', 'f'), ('男', 'm')], max_length=1),
        ),
    ]
