# Generated by Django 2.0.2 on 2020-05-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0006_auto_20200516_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='num',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
