# Generated by Django 2.0.2 on 2020-05-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0008_auto_20200518_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='dep',
            field=models.CharField(choices=[('sales', '営業'), ('pr', '広報'), ('dev', '開発')], max_length=5),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='job',
            field=models.CharField(choices=[('regular', '一般'), ('administrator', '組織長')], max_length=13),
        ),
    ]
